apiVersion: v2
name: intrexx-portal
description: A Helm chart for deploying Intrexx Portal applications on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - intrexx
  - portal
  - application
maintainers:
  - name: Intrexx Support
    email: support@unitedplanet.com
dependencies:
  - name: postgresql
    version: ~12.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: solr
    version: ~1.5.2
    repository: https://charts.bitnami.com/bitnami
    condition: solr.enabled
  - name: zookeeper
    version: ~11.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
