# Default values for intrexx-portal
replicaCount: 1

image:
  repository: unitedplanet/intrexx
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  webconnectorPort: 1337
  restPort: 8101
  odataPort: 9090

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "INTREXX_SESSION"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
  hosts:
    - host: intrexx.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

# Intrexx specific configuration
intrexx:
  portalName: portal
  portalBaseUrl: http://intrexx.local
  distributed: true
  
  # Application management
  applications:
    # Pre-installed applications
    preInstall:
      enabled: false
      apps: []
      # - name: crm
      #   version: "1.0.0"
      #   packageUrl: "https://example.com/packages/crm-1.0.0.zip"
      #   configMap: ""  # Optional: reference to existing ConfigMap with app config
    
    # Application lifecycle management
    lifecycle:
      enabled: true
      deployerImage: "unitedplanet/intrexx:latest"
      serviceAccount: ""  # Uses chart serviceAccount if empty
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 512Mi

# Database configuration
postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: intrexx
  primary:
    persistence:
      size: 8Gi

# External database configuration (if postgresql.enabled=false)
externalDatabase:
  host: ""
  port: 5432
  user: postgres
  password: postgres
  database: intrexx

# Solr configuration
solr:
  enabled: true
  authentication:
    enabled: true
    adminUsername: solr
    adminPassword: SolrRocks
  replicaCount: 1
  persistence:
    size: 8Gi

# Zookeeper configuration
zookeeper:
  enabled: true
  replicaCount: 1
  auth:
    enabled: true
    clientUser: solr
    clientPassword: SolrRocks
  persistence:
    size: 8Gi

# Monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
  
# Backup configuration
backup:
  enabled: false
  schedule: "0 1 * * *"  # Daily at 1 AM
  retention: 7  # Number of backups to keep
  destination: "/backups"
  includeApplications: true
  includeDatabase: true
  includeSolr: true
